#!/bin/bash

function dd_instl(){
    bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/pzwsquare/dd/master/dd) -d 10 -v 64 -p 'dd' -a
}

toolsMenu() {

    Mainmenu=$(whiptail --clear --ok-button "确定" --backtitle "version:20200714" --title "dt服务端v2.3" --menu --nocancel "
    " 22 86 5\
        "1" " 安装debian10（登录密码：dd）"\
        "5" " 退出" 3>&1 1>&2 2>&3)
    case $Mainmenu in
        1)
        dd_instl
        ;;
        esac
}

# osdist


toolsMenu
